# Generated by Django 4.0.2 on 2022-02-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0003_estudiante_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='fecha',
            new_name='fechaMatricula',
        ),
    ]
