# Generated by Django 4.0.2 on 2022-02-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0004_rename_fecha_matricula_fechamatricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='fechaMatricula',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
