# Generated by Django 4.0.2 on 2022-02-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0005_alter_matricula_fechamatricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='fechaMatricula',
        ),
    ]
